replicaCount: 1

image:
  repository: namespace-class-controller
  tag: dev
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: namespace-class-controller

manager:
  args:
    - --leader-elect
  resources: {}

policy:
  allowGVKs: []
  denyGVKs:
    - rbac.authorization.k8s.io/v1/ClusterRoleBinding
