apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-manager
  labels:
    app.kubernetes.io/name: namespace-class
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - namespaceclass.akuity.io
    resources:
      - namespaceclasses
      - namespaceclasses/status
      - namespaceclassbindings
      - namespaceclassbindings/status
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete

