apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: namespace-class
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: namespace-class
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: namespace-class
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: healthz
              containerPort: 8081
              protocol: TCP
          args:
{{- range .Values.manager.args }}
            - {{ . | quote }}
{{- end }}
{{- if .Values.policy.allowGVKs }}
            - {{ printf "--policy-allow-gvks=%s" (join "," .Values.policy.allowGVKs) | quote }}
{{- end }}
{{- if .Values.policy.denyGVKs }}
            - {{ printf "--policy-deny-gvks=%s" (join "," .Values.policy.denyGVKs) | quote }}
{{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
          readinessProbe:
            httpGet:
              path: /readyz
              port: healthz
          resources:
{{ toYaml .Values.manager.resources | indent 12 }}
